### PR TITLE
Positioning of Checkbox labels to the right of checkbox on Horizontal Theme

### PR DESCRIPTION
**Pull request by jattwood**
Please review updates with thanks...

### CODE REVIEW

**Comment by vipervf1** [comment]
@jattwood Can you update the package.nuspec file to rev the version number to 1.0.2 and add a release notes description saying "Updated checkbox labels to the right of checkbox on Horizontal Theme"

**Comment by jattwood** [comment]
Done.

**Comment by vipervf1** [comment]
@jattwood This is merged and released. Please pull it into your project and give it one last test!

**Comment by jattwood** [comment]
Excellent. Will do.

Thanks,

Jamie

**Pull request merged**
